### ISSUE TITLE
Error: Unable to open '': Document with resource image-preview://image-preview does not exist.

### ISSUE THREAD

**Issue by Alex-Zaharow** [buzzfrog/vscode-imagepreview#1]
Hello.
Thank you for your component, but it is not working for me. When I try to open image I get error:

![2016-03-24_152101](https://cloud.githubusercontent.com/assets/1136253/14016931/6c451284-f1d4-11e5-9b63-5506f0b1e85f.png)

Image is png file:

![2016-03-24_152555](https://cloud.githubusercontent.com/assets/1136253/14016969/c864acf0-f1d4-11e5-9061-49fb879b8842.png)

Can you fix it? Or may be I do something wrong?

**Comment by buzzfrog** [comment]
Hi
It doesn't work if the file don't have the file extension telling what kind of image file it is.
/dag

**Comment by Alex-Zaharow** [comment]
Thank you.
Sorry for a fun issue. I have read a source code later and found this too.
